name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install dependencies
        run: npm install

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Docker Scout
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          mkdir -p ~/.docker/cli-plugins
          sudo cp ~/.docker/cli-plugins/docker-scout /usr/local/bin/
          docker-scout version

      - name: Docker Scout Scan (source code)
        run: |
          docker-scout quickview fs://.
          docker-scout cves fs://.

      - name: Docker build and push
        run: |
          docker build -t myntra .
          docker tag myntra abhishek450/myntra:latest
          docker push abhishek450/myntra:latest

      - name: Docker Scout Scan (image)
        run: |
          docker-scout quickview abhishek450/myntra:latest
          docker-scout cves abhishek450/myntra:latest

  deploy:
    name: Deploy to EKS
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Docker image
        run: docker pull abhishek450/myntra:latest

      - name: Run container locally
        run: docker run -d --name myntra -p 3000:3000 abhishek450/myntra:latest

      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-service.yml
